language: node_js
node_js:
    - lts/*
branches:
  only:
    - master
    - develope
notifications:
  email:
    recipients:
      - marlenek@consol.de
      - julian.liebich@consol.de
    on_success: never
    on_failure: always